### ISSUE TITLE
what server options referring to?

### ISSUE THREAD

**Issue by faststare** [na2axl/jsondb-js#1]
jdb.createServer('server_name', 'username', 'password', connect);

can you give simple live example?

**Comment by na2axl** [comment]
Hi!
jdb.createServer() is used to create a new server (a folder in which all databases will be stored). For example, we want to create the server  **test** with the username **root** and no password, we have to do like this: jdb.createServer('test', 'root', '');
If you want to connect to the server directly after the creation, you have to set the connect parameter to **true**: jdb.createServer('test', 'root', '', true);
In this case jdb.createServer() will return an instance of the server connection.
I hope this will help you!

**Comment by ruslankonev** [comment]
If «Server» is a folder, what and why usage a username and password fields? It is a plain-text fields which test only equality of strings?

**Comment by na2axl** [comment]
Yes @ruslankonev , but this is used to help users to be ready for the use of the next version of jsondb, which include distant server connection (with username and password) with [jsondb-server](https://github.com/na2axl/jsondb-server).
